#!/usr/bin/env python3
"""Generate opcodes.h and disasm_tables.h from docs/dev/Opcodes.json."""

import json
import os
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
JSON_PATH = REPO_ROOT / "docs" / "dev" / "Opcodes.json"
OUTPUT_PATH = REPO_ROOT / "src" / "opcodes.h"
DISASM_OUTPUT_PATH = REPO_ROOT / "src" / "disasm_tables.h"


def format_operand_name(op):
    name = op["name"]
    if op.get("immediate") is False:
        if op.get("increment"):
            return f"{name}_INC"
        elif op.get("decrement"):
            return f"{name}_DEC"
        return f"{name}_IND"
    return name


def make_enum_name(opcode_hex, entry, prefix_tag=""):
    mnemonic = entry["mnemonic"]
    operands = entry.get("operands", [])
    parts = [mnemonic]
    for op in operands:
        parts.append(format_operand_name(op))
    name = "_".join(parts)
    if prefix_tag:
        name = f"{prefix_tag}_{name}"
    else:
        name = f"OP_{name}"

    name = name.replace('$', 'S')
    return name


def get_opcode_cycles(entry, taken=True):
    """
    Returns cycle count for an opcode entry.
    If 'taken' is True, returns taken cycles (or standard cycles).
    If 'taken' is False, returns untaken cycles if present.
    """
    cycles = entry.get("cycles", [0])
    if not cycles:
        return 0
    if len(cycles) > 1:
        # Most Game Boy opcode tables format conditional branches as [taken, untaken]
        return cycles[0] if taken else cycles[1]
    return cycles[0]


DISASM_KIND_TO_C = {
    "IMM8": "DISASM_ARG_IMM8",
    "IMM16": "DISASM_ARG_IMM16",
    "ADDR16": "DISASM_ARG_ADDR16",
    "ADDR8": "DISASM_ARG_ADDR8",
    "REL8": "DISASM_ARG_REL8",
    "SIGNED": "DISASM_ARG_SIGNED",
}


def make_disasm_fmt(opcode_hex, entry):
    """Build the printf-style format string and argument kinds for one opcode.

    Literals (register names, conditions, RST targets) are baked into the
    string; data bytes become printf arguments classified by kind so the C
    side can fetch and format them.
    """
    mnemonic = entry["mnemonic"]
    operands = entry.get("operands", [])

    if mnemonic.startswith("ILLEGAL_"):
        return f"DB ${opcode_hex[2:]}", []
    if mnemonic == "STOP":
        # The padding byte after STOP is never interesting; the bytes column
        # of the disassembly view already shows it.
        return "STOP", []
    if mnemonic == "PREFIX":
        return "PREFIX", []

    chunks = []
    kinds = []
    suppress_comma = False

    for i, op in enumerate(operands):
        name = op["name"]
        immediate = op.get("immediate", True)
        increment = op.get("increment", False)
        decrement = op.get("decrement", False)

        if i == 0 or suppress_comma:
            sep = ""
        else:
            sep = ","
        suppress_comma = False

        kind = None
        if name == "HL" and immediate and mnemonic == "JP":
            # The JSON marks E9's operand as immediate, but it is really (HL)
            text, kind = "(HL)", None
        elif name == "a16":
            text = "$%04X" if immediate else "($%04X)"
            kind = "ADDR16"
        elif name == "a8":
            text = "($%04X)"  # LDH high address: rendered as ($FFnn)
            kind = "ADDR8"
        elif name == "n8":
            text, kind = "$%02X", "IMM8"
        elif name == "n16":
            text, kind = "$%04X", "IMM16"
        elif name == "e8":
            if mnemonic == "JR":
                text, kind = "$%04X", "REL8"  # branch target address
            else:
                text, kind = "%+d", "SIGNED"  # ADD SP,e8 / LD HL,SP+e8
        elif name == "SP" and increment:
            # LD HL,SP+e8: emit "SP" bare and swallow the comma before the e8
            text, kind = "SP", None
            suppress_comma = True
        elif not immediate:
            if increment:
                text, kind = f"({name}+)", None
            elif decrement:
                text, kind = f"({name}-)", None
            else:
                text, kind = f"({name})", None
        else:
            text, kind = name, None

        chunks.append(sep + text)
        if kind:
            kinds.append(kind)

    fmt = mnemonic + ((" " + "".join(chunks)) if chunks else "")
    return fmt, kinds


def disasm_entry_line(opcode_hex, entry):
    fmt, kinds = make_disasm_fmt(opcode_hex, entry)
    kinds_c = [DISASM_KIND_TO_C[k] for k in kinds]
    kinds_c += ["DISASM_ARG_NONE"] * (2 - len(kinds_c))
    escaped = fmt.replace("\\", "\\\\").replace('"', '\\"')
    return '    /* %s */ { "%s", %d, %d, { %s, %s } },' % (
        opcode_hex,
        escaped,
        entry["bytes"],
        len(kinds),
        kinds_c[0],
        kinds_c[1],
    )


def main():
    with open(JSON_PATH) as f:
        data = json.load(f)

    lines = [
        "#ifndef OPCODES_H",
        "#define OPCODES_H",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
        "// Auto-generated by scripts/generate_opcodes.py",
        "// Do not edit manually.",
        "// Reference: https://gbdev.io/gb-opcodes/optables/",
        "",
    ]

    # Unprefixed opcodes
    lines.append("enum {")
    unprefixed = data.get("unprefixed", {})
    for hex_val in sorted(unprefixed.keys(), key=lambda h: int(h, 16)):
        entry = unprefixed[hex_val]
        name = make_enum_name(hex_val, entry, prefix_tag="OP")
        lines.append(f"    {name} = {hex_val},")
    lines.append("};")
    lines.append("")

    # CB-prefixed opcodes
    cbprefixed = data.get("cbprefixed", {})
    if cbprefixed:
        lines.append("enum {")
        for hex_val in sorted(cbprefixed.keys(), key=lambda h: int(h, 16)):
            entry = cbprefixed[hex_val]
            name = make_enum_name(hex_val, entry, prefix_tag="OP_CB")
            lines.append(f"    {name} = 0xCB{hex_val[2:]},")
        lines.append("};")
        lines.append("")

    # Standard cycle lookup function
    lines.append("static inline uint8_t get_opcode_cycles(uint8_t opcode, bool condition_met) {")
    lines.append("    switch (opcode) {")
    for hex_val in sorted(unprefixed.keys(), key=lambda h: int(h, 16)):
        entry = unprefixed[hex_val]
        cycles_taken = get_opcode_cycles(entry, taken=True)
        cycles_untaken = get_opcode_cycles(entry, taken=False)

        if cycles_taken != cycles_untaken:
            lines.append(f"        case {hex_val}: return condition_met ? {cycles_taken} : {cycles_untaken};")
        else:
            lines.append(f"        case {hex_val}: return {cycles_taken};")
    lines.append("        default: return 0;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # CB-prefixed cycle lookup function
    if cbprefixed:
        lines.append("static inline uint8_t get_cb_opcode_cycles(uint8_t cb_opcode) {")
        lines.append("    switch (cb_opcode) {")
        for hex_val in sorted(cbprefixed.keys(), key=lambda h: int(h, 16)):
            entry = cbprefixed[hex_val]
            cycles = get_opcode_cycles(entry, taken=True)
            lines.append(f"        case {hex_val}: return {cycles};")
        lines.append("        default: return 0;")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    lines.append("#endif // OPCODES_H")
    lines.append("")

    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {OUTPUT_PATH}")
    print(f"  Unprefixed: {len(unprefixed)} opcodes")
    print(f"  CB-prefixed: {len(cbprefixed)} opcodes")

    # --- Disassembler tables ---
    dlines = [
        "#ifndef DISASM_TABLES_H",
        "#define DISASM_TABLES_H",
        "",
        "#include <stdint.h>",
        "",
        "// Auto-generated by scripts/generate_opcodes.py",
        "// Do not edit manually.",
        "// Reference: https://gbdev.io/gb-opcodes/optables/",
        "",
        "typedef enum {",
        "    DISASM_ARG_NONE = 0, // no printf argument",
        "    DISASM_ARG_IMM8,     // $%02X - raw immediate byte",
        "    DISASM_ARG_IMM16,    // $%04X - raw little-endian word",
        "    DISASM_ARG_ADDR16,   // $%04X / ($%04X) - absolute address",
        "    DISASM_ARG_ADDR8,    // $%04X - high address (0xFF00+n)",
        "    DISASM_ARG_REL8,     // $%04X - PC-relative branch target",
        "    DISASM_ARG_SIGNED,   // %+d - signed immediate offset",
        "} disasm_arg_kind;",
        "",
        "typedef struct {",
        '    const char* fmt; // printf-style text, e.g. "LD A,$%02X"',
        "    uint8_t bytes;        // total instruction length in bytes (1-3)",
        "    uint8_t arg_count;    // number of printf arguments in fmt (0-2)",
        "    uint8_t arg_kinds[2]; // disasm_arg_kind of each argument, in order",
        "} disasm_op;",
        "",
        "static const disasm_op disasm_table[256] = {",
    ]
    for hex_val in sorted(unprefixed.keys(), key=lambda h: int(h, 16)):
        dlines.append(disasm_entry_line(hex_val, unprefixed[hex_val]))
    dlines.append("};")
    dlines.append("")
    dlines.append("static const disasm_op disasm_cb_table[256] = {")
    for hex_val in sorted(cbprefixed.keys(), key=lambda h: int(h, 16)):
        dlines.append(disasm_entry_line(hex_val, cbprefixed[hex_val]))
    dlines.append("};")
    dlines.append("")
    dlines.append("#endif // DISASM_TABLES_H")
    dlines.append("")

    with open(DISASM_OUTPUT_PATH, "w") as f:
        f.write("\n".join(dlines))

    print(f"Generated {DISASM_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
