#!/usr/bin/env python3
"""Generate opcodes.h from docs/Opcodes.json."""

import json
import os
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
JSON_PATH = REPO_ROOT / "docs" / "Opcodes.json"
OUTPUT_PATH = REPO_ROOT / "src" / "opcodes.h"


def format_operand_name(op):
    name = op["name"]
    if op.get("immediate") is False:
        if op.get("increment"):
            return f"{name}_INC"
        elif op.get("decrement"):
            return f"{name}_DEC"
        return f"{name}_IND"
    return name


def make_enum_name(opcode_hex, entry, prefix_tag=""):
    mnemonic = entry["mnemonic"]
    operands = entry.get("operands", [])
    parts = [mnemonic]
    for op in operands:
        parts.append(format_operand_name(op))
    name = "_".join(parts)
    if prefix_tag:
        name = f"{prefix_tag}_{name}"
    else:
        name = f"OP_{name}"

    name = name.replace('$', 'S')
    return name


def main():
    with open(JSON_PATH) as f:
        data = json.load(f)

    lines = [
        "#ifndef OPCODES_H",
        "#define OPCODES_H",
        "",
        "// Auto-generated by scripts/generate_opcodes.py",
        "// Do not edit manually.",
        "// Reference: https://gbdev.io/gb-opcodes/optables/",
        "",
    ]

    # Unprefixed opcodes
    lines.append("enum {")
    unprefixed = data.get("unprefixed", {})
    for hex_val in sorted(unprefixed.keys(), key=lambda h: int(h, 16)):
        entry = unprefixed[hex_val]
        name = make_enum_name(hex_val, entry, prefix_tag="OP")
        lines.append(f"    {name} = {hex_val},")
    lines.append("};")
    lines.append("")

    # CB-prefixed opcodes
    cbprefixed = data.get("cbprefixed", {})
    if cbprefixed:
        lines.append("enum {")
        for hex_val in sorted(cbprefixed.keys(), key=lambda h: int(h, 16)):
            entry = cbprefixed[hex_val]
            name = make_enum_name(hex_val, entry, prefix_tag="OP_CB")
            lines.append(f"    {name} = 0xCB{hex_val[2:]},")
        lines.append("};")
        lines.append("")

    lines.append("#endif // OPCODES_H")
    lines.append("")

    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {OUTPUT_PATH}")
    print(f"  Unprefixed: {len(unprefixed)} opcodes")
    print(f"  CB-prefixed: {len(cbprefixed)} opcodes")


if __name__ == "__main__":
    main()
