#!/usr/bin/env python3
"""Generate opcodes.h from docs/Opcodes.json."""

import json
import os
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
JSON_PATH = REPO_ROOT / "docs" / "Opcodes.json"
OUTPUT_PATH = REPO_ROOT / "src" / "opcodes.h"


def format_operand_name(op):
    name = op["name"]
    if op.get("immediate") is False:
        if op.get("increment"):
            return f"{name}_INC"
        elif op.get("decrement"):
            return f"{name}_DEC"
        return f"{name}_IND"
    return name


def make_enum_name(opcode_hex, entry, prefix_tag=""):
    mnemonic = entry["mnemonic"]
    operands = entry.get("operands", [])
    parts = [mnemonic]
    for op in operands:
        parts.append(format_operand_name(op))
    name = "_".join(parts)
    if prefix_tag:
        name = f"{prefix_tag}_{name}"
    else:
        name = f"OP_{name}"

    name = name.replace('$', 'S')
    return name


def get_opcode_cycles(entry, taken=True):
    """
    Returns cycle count for an opcode entry.
    If 'taken' is True, returns taken cycles (or standard cycles).
    If 'taken' is False, returns untaken cycles if present.
    """
    cycles = entry.get("cycles", [0])
    if not cycles:
        return 0
    if len(cycles) > 1:
        # Most Game Boy opcode tables format conditional branches as [taken, untaken]
        return cycles[0] if taken else cycles[1]
    return cycles[0]


def main():
    with open(JSON_PATH) as f:
        data = json.load(f)

    lines = [
        "#ifndef OPCODES_H",
        "#define OPCODES_H",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
        "// Auto-generated by scripts/generate_opcodes.py",
        "// Do not edit manually.",
        "// Reference: https://gbdev.io/gb-opcodes/optables/",
        "",
    ]

    # Unprefixed opcodes
    lines.append("enum {")
    unprefixed = data.get("unprefixed", {})
    for hex_val in sorted(unprefixed.keys(), key=lambda h: int(h, 16)):
        entry = unprefixed[hex_val]
        name = make_enum_name(hex_val, entry, prefix_tag="OP")
        lines.append(f"    {name} = {hex_val},")
    lines.append("};")
    lines.append("")

    # CB-prefixed opcodes
    cbprefixed = data.get("cbprefixed", {})
    if cbprefixed:
        lines.append("enum {")
        for hex_val in sorted(cbprefixed.keys(), key=lambda h: int(h, 16)):
            entry = cbprefixed[hex_val]
            name = make_enum_name(hex_val, entry, prefix_tag="OP_CB")
            lines.append(f"    {name} = 0xCB{hex_val[2:]},")
        lines.append("};")
        lines.append("")

    # Standard cycle lookup function
    lines.append("static inline uint8_t get_opcode_cycles(uint8_t opcode, bool condition_met) {")
    lines.append("    switch (opcode) {")
    for hex_val in sorted(unprefixed.keys(), key=lambda h: int(h, 16)):
        entry = unprefixed[hex_val]
        cycles_taken = get_opcode_cycles(entry, taken=True)
        cycles_untaken = get_opcode_cycles(entry, taken=False)

        if cycles_taken != cycles_untaken:
            lines.append(f"        case {hex_val}: return condition_met ? {cycles_taken} : {cycles_untaken};")
        else:
            lines.append(f"        case {hex_val}: return {cycles_taken};")
    lines.append("        default: return 0;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # CB-prefixed cycle lookup function
    if cbprefixed:
        lines.append("static inline uint8_t get_cb_opcode_cycles(uint8_t cb_opcode) {")
        lines.append("    switch (cb_opcode) {")
        for hex_val in sorted(cbprefixed.keys(), key=lambda h: int(h, 16)):
            entry = cbprefixed[hex_val]
            cycles = get_opcode_cycles(entry, taken=True)
            lines.append(f"        case {hex_val}: return {cycles};")
        lines.append("        default: return 0;")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    lines.append("#endif // OPCODES_H")
    lines.append("")

    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {OUTPUT_PATH}")
    print(f"  Unprefixed: {len(unprefixed)} opcodes")
    print(f"  CB-prefixed: {len(cbprefixed)} opcodes")


if __name__ == "__main__":
    main()
